source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'MQTTClientmacOS' do
	pod 'SocketRocket', '0.7.0'
    
    target 'MQTTClientmacOSTests' do
        inherit! :search_paths
    end
end

target 'MQTTClientiOS' do
    pod 'SocketRocket', '0.7.0'
    
    target 'MQTTClientiOSTests' do
        inherit! :search_paths
    end
end

target 'MQTTClienttvOS' do
    pod 'SocketRocket', '0.7.0'
    
    target 'MQTTClienttvOSTests' do
        inherit! :search_paths
    end
end
